name: richmeade
favicon: null
layout_spectrum: 0.041431998601183295
typography_spectrum: 0.11160937952809036
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors: []
  brandStrength: 0.12014159839600325
  lightness: 0.4445927587803453
  saturation: 0.8284934074617922
  rhythmicContrast: 0.18476589443162084
purpose: []
